name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout project
      uses: actions/checkout@v1
    - name: composer install missing files
      run: composer install
    - name: run tests
      run: /usr/bin/php -f bin/phpunit > output.txt
