name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v1
    - name: Copy config
      run: cp config/_config.php config/config.php
    - uses: php-actions/phpunit@v9
